### ISSUE TITLE
published whl doesnt run due to namespace issues

### ISSUE THREAD

**Issue by jack-broadway** [jack-broadway/vyos-modular#10]
The current version publish to pypi does not run as its not finding the namespace package properly

```console
Traceback (most recent call last):
  File "/tmp/vyos-build/venv/bin/vyos-modular", line 5, in <module>
    from vyos_modular.main import main
  File "/tmp/vyos-build/venv/lib/python3.10/site-packages/vyos_modular/main.py", line 8, in <module>
    import vyos_modular.iso_build.builder
ModuleNotFoundError: No module named 'vyos_modular.iso_build'
```

For a tempory workaround, install by cloning the repo and using `pip install -e .`

**Comment by jack-broadway** [comment]
Fixed in v2.1.1
